version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local_network
    restart: on-failure:3

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    depends_on:
      - postgres
    environment:
      PGWEB_DATABASE_URL: postgres://username:password@postgres:5432/template?sslmode=disable
    ports:
      - 8085:8081
    networks:
      - local_network
    restart: on-failure:3

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - local_network
    restart: on-failure:3

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    ports:
      - 8001:8001
    depends_on:
      - redis
    networks:
      - local_network
    restart: on-failure:3

networks:
  local_network:

volumes:
  postgres_data:
  redis_data:
